sudo: required
services:
    - docker

before_install:
    - docker build -t nexter21/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nexter21/react-test npm test

after_success:
    - docker build -t nexter21/multi-client ./client
    - docker build -t nexter21/multi-nginx ./nginx
    - docker build -t nexter21/multi-server ./server
    - docker build -t nexter21/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push nexter21/multi-client
    - docker push nexter21/multi-nginx
    - docker push nexter21/multi-server
    - docker push nexter21/multi-worker

